### ISSUE TITLE
googleAnalytics.html partial layout is missing

### ISSUE THREAD

**Issue by mattischrome** [nstrayer/tuftesque#10]
This prevents blogdown from serving the site. Even using a blank file works. Or comment out the line that calls it in header.includes.html

**Comment by rosseji** [comment]
I have the same issue:

```r
Started building sites ...
ERROR 2017/10/10 07:03:18 Error while rendering "page": template: theme/_default/single.html:2:3: executing "theme/_default/single.html" at <partial "header.html...>: error calling partial: template: theme/partials/header.html:5:5: executing "theme/partials/header.html" at <partial "header.incl...>: error calling partial: template: theme/partials/header.includes.html:33:3: executing "theme/partials/header.includes.html" at <partial "googleAnaly...>: error calling partial: Partial "googleAnalytics.html" not found```

**Comment by rosseji** [comment]
@mattischrome I tried your suggestions:

When I comment out the line that cals the googleAnalytics.html 

or 

add a blank html file I get:

```
Started building sites ...
ERROR 2017/10/11 10:08:33 Error while rendering "page": template: theme/_default/single.html:6:3: executing "theme/_default/single.html" at <partial "brand.html"...>: error calling partial: template: theme/partials/brand.html:5:46: executing "theme/partials/brand.html" at <relURL>: wrong number of args for relURL: want 1 got 0
```

**Comment by nstrayer** [comment]
Shoot. I’ll look into this this morning. I must have forgotten to wrap the google analytics partial in an if statement checking for it being included.

**Comment by nstrayer** [comment]
So this should be fixed now. The issue was I thought I had put a blank google analytics partial in the files but apparently, I forgot to. The reason for putting a blank one in is hugo will automatically pull one in your local `/layouts/` folder but if you don't have one in there it needs something to put in. Rather than put an if statement checking I just send it a blank one. Try it out and let me know if the problem is fixed.

**Comment by rosseji** [comment]
@nstrayer Thanks for the changes. I'm still getting this error...

```
Started building sites ...
ERROR 2017/10/12 12:21:09 Error while rendering "page": template: theme/_default/single.html:6:3: executing "theme/_default/single.html" at <partial "brand.html"...>: error calling partial: template: theme/partials/brand.html:5:46: executing "theme/partials/brand.html" at <relURL>: wrong number of args for relURL: want 1 got 0
```

**Comment by rosseji** [comment]
@nstrayer Thanks changes work!

I've found there is a bug when loading the site through the new Rstudio blogdown project engine...

<img width="525" alt="screen shot 2017-10-15 at 9 41 41 pm" src="https://user-images.githubusercontent.com/21113591/31584031-aecd296e-b1f1-11e7-89f8-d1bd1d2e883d.png">

But installing this theme via `blogdown::install_theme("nstrayer/tuftesque")` works.

Thanks again

**Comment by nstrayer** [comment]
Interesting. I havent actually used that so I probably have to modify some stuff to fit it. I'm going to close this issue and reopen a new one for this. Thanks for the heads up!
